services:
  task-service:
    image: '${TASK_SERVICE_IMAGE}'
    container_name: 'task-service'
    environment:
      - 'POSTGRES_URL=jdbc:postgresql://postgres:5432/postgres-task-tracker'
      - 'POSTGRES_USERNAME=${POSTGRES_USERNAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    ports:
      - '8080:8080'
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: 'postgres:latest'
    container_name: 'postgres-task-tracker'
    environment:
      - 'POSTGRES_DB=postgres-task-tracker'
      - 'POSTGRES_USER=${POSTGRES_USERNAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    ports:
      - '5432:5432'
    volumes:
      - /task-tracker:/var/lib/postgresql/data
    restart: unless-stopped

  zookeeper:
    image: bitnami/zookeeper:3.8.0
    container_name: task-tracker-zookeeper
    restart: on-failure
    ports:
      - "2181:2181"
    environment:
      ZOO_PORT: 2181
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    image: bitnami/kafka:3.8.0
    container_name: task-tracker-kafka
    restart: on-failure
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "my-zookeeper:2181"
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_TOPIC: "EMAIL_SENDING_TASKS"
      ALLOW_PLAINTEXT_LISTENER: "yes"
