server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: task-service
          uri: lb://TASK-SERVICE
          predicates:
            - Path=/api/v1/tasks/**
          filters:
            - Authentication

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - Authentication

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

urls:
  validate: http://localhost:8080/api/v1/auth/validate
