server:
  port: 8880
  servlet:
    context-path: /scheduler-service

spring:
  application:
    name: scheduler-service
  kafka:
    bootstrap-servers: ${KAFKA_ADDRESS}
    topics:
      sending-tasks: EMAIL_SENDING_TASKS

logging:
  level:
    org.springframework.web: "debug"
    org.hibernate:
      SQL: "debug"
