server:
  port: 8082
  servlet:
    context-path: /task-tracker

spring:
  application:
    name: security-service
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: db/changelog.xml

logging:
  level:
    org.springframework.web: "debug"
    org.hibernate:
      SQL: "debug"

token:
  signing:
    value: "TmFydmEgb24gbGlubiBFZXN0aSBraXJkZW9zYXMgSWRhLVZpcnUgbWFha29ubmFzIE5hcnZhIGrDtWUgYWxhbWpvb2tzdWwgRWVzdGktVmVuZW1hYSBwaWlyaSDDpMOkcmVzLg=="
